baseURL = 'https://simondelhaye.dev/'
languageCode = 'fr-FR'
title = 'Blog de Simon DELHAYE'
theme = 'anatole'

[params]
title = "Blog de Simon Delhaye"
author = "Simon Delhaye"
description = ""
profilePicture = "/images/profile.png"